### ISSUE TITLE
<pre> blocks has too many carriage-returns

### ISSUE THREAD

**Issue by brianblank** [hafaio/repub#4]
Web Page has `<pre>` tag for pre-formatted text.  However, the conversion from webpage to ePub file using this tool is placing each word on a separate line.   Screen prints below show both the original web page format as well as the converted ePub format.

![WebPage](https://github.com/hafaio/repub/assets/6259947/2ba6d00f-3eec-47df-8973-25264bbdbc0a)

![ePubView](https://github.com/hafaio/repub/assets/6259947/ced2d28f-6cf2-4b1f-b368-c054275dff85)

**Comment by erikbrinkman** [comment]
That's not great... There seem to be two, potentially related problems.
1. each span block is causing a new line (what you're actually talking about)
2. each line break is counting double.

The actual ebook itself has what seems like the right xhtml to render this, but it seems like default ebook stying might treat spans (or spans inside pre's) as block elements. Most ebook renderers don't have nice developer tools for understanding why they render a certain way, but the behavior seems consistent, so I'll try to dig in.

In the worst case I may have to add an option that strips spans from inside pre's 😕

**Comment by erikbrinkman** [comment]
After looking into this more, the problem was that I was pretty printing the xml, inserting extra whitespace, which would be harmless, except in `<pre>` tags. As of the next version 3.0.2, this should be fixed.

**Comment by brianblank** [comment]
Thank you so much for your help and fast response.
